import type { Metadata } from "next"
import Head from "./pages/_document"
import "./globals.css"
import { MainLayout } from "./components/layouts/MainLayout"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head />
      <body>
        <MainLayout />
        {children}
      </body>
    </html>
  )
}
